global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
        send_resolved: true
        username: 'AlertManager'

additionalScrapeConfigs:
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['107.21.49.19:8080']
